### ISSUE TITLE
mail.from[0].address

### ISSUE THREAD

**Issue by bluefish007** [vijayakumarit/mail-listener6#1]
mail.from[0].address (to get the mail address) is not working

**Comment by vijayakumarit** [comment]
Can you try this mail.from.address

**Comment by bluefish007** [comment]
Unfortunately it is not working!

But I grab the information now from header...

**Comment by nayaganov** [comment]
> Unfortunately it is not working!
> 
> But I grab the information now from header...

try mail.from.value[0].address

**Comment by bluefish007** [comment]
@nayaganov It works! Thank you!
